[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version ="4.5.4" , features = ["cargo", "derive"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = {version = "1.0.118"}